//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cribbage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public System.Guid Id { get; set; }
        public Suit Suit { get; set; }
        public CardValue Value { get; set; }
        public CardScore Points { get; set; }
    }
}
