//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cribbage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Players = new HashSet<Player>();
            this.Hands = new HashSet<GameHand>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MatchId { get; set; }
        public GameState State { get; set; }
        public bool AllowMuggins { get; set; }
        public System.Guid CurrentHandId { get; set; }
        public System.Guid CurrentDealerId { get; set; }
        public int Index { get; set; }
    
        public virtual Match Match { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameHand> Hands { get; set; }
        public virtual GameHand CurrentHand { get; set; }
        public virtual Player CurrentDealer { get; set; }
    }
}
