//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cribbage.Entities
{
    using System;
    
    public enum ScoreType : int
    {
        None = 0,
        Go = 1,
        Fifteen = 2,
        Flush = 3,
        LastCard = 4,
        Nibs = 5,
        Nobs = 6,
        Pair = 7,
        Quadruple = 8,
        Straight = 9,
        ThirtyOne = 10,
        Triple = 11
    }
}
