
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace Cribbage.Web.Model
{
    using System;
    
    public enum GameState : int
    {
        New = 0,
        InProgress = 1,
        Cancelled = 2,
        Finished = 3
    }
}
