//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cribbage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Hands = new HashSet<PlayerHand>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid GameId { get; set; }
        public System.Guid UserId { get; set; }
        public int GameOrder { get; set; }
        public int GameTotal { get; set; }
        public System.Guid CribId { get; set; }
        public System.Guid CurrentHandId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerHand> Hands { get; set; }
        public virtual PlayerHand Crib { get; set; }
        public virtual PlayerHand CurrentHand { get; set; }
    }
}
